"""Synthetic sample data for the mock FACETS gateway.

Every person, member ID, NPI, tax ID and phone number here is fictional and
generated for testing. Never load real PHI into this file.
"""

PLAN_YEAR = "2026"

MEMBERS = {
    "MEM-987654": {
        "memberId": "MEM-987654",
        "subscriberId": "SUB-987654",
        "firstName": "Sarah",
        "lastName": "Jenkins",
        "dateOfBirth": "1984-03-12",
        "phone": "+15555550101",
        "relationship": "Subscriber",
        "groupId": "GRP-1001",
        "groupName": "Northwind Traders",
        "planId": "PPO1500",
        "planDescription": "Enterprise Choice PPO 1500",
        "productType": "PPO",
        "status": "Active",
        "coverageEffectiveDate": "2026-01-01",
        "coverageTermDate": None,
        "pcp": None,
        "accumulators": {
            "deductibleIndividualTotal": 1500.00,
            "deductibleIndividualMet": 1150.00,
            "deductibleFamilyTotal": 3000.00,
            "deductibleFamilyMet": 1890.00,
            "outOfPocketIndividualTotal": 4000.00,
            "outOfPocketIndividualMet": 2200.00,
            "outOfPocketFamilyTotal": 8000.00,
            "outOfPocketFamilyMet": 3105.00,
        },
    },
    "MEM-445566": {
        "memberId": "MEM-445566",
        "subscriberId": "SUB-445566",
        "firstName": "Miguel",
        "lastName": "Alvarez",
        "dateOfBirth": "1979-11-02",
        "phone": "+15555550102",
        "relationship": "Subscriber",
        "groupId": "GRP-2002",
        "groupName": "Contoso Manufacturing",
        "planId": "HMO500",
        "planDescription": "Select Care HMO 500",
        "productType": "HMO",
        "status": "Active",
        "coverageEffectiveDate": "2025-07-01",
        "coverageTermDate": None,
        "pcp": {
            "npi": "1234567893",
            "name": "Dr. Alana Brooks",
            "practice": "Riverside Family Medicine",
            "phone": "+15555550190",
        },
        "accumulators": {
            "deductibleIndividualTotal": 500.00,
            "deductibleIndividualMet": 500.00,
            "deductibleFamilyTotal": 1000.00,
            "deductibleFamilyMet": 640.00,
            "outOfPocketIndividualTotal": 3500.00,
            "outOfPocketIndividualMet": 910.00,
            "outOfPocketFamilyTotal": 7000.00,
            "outOfPocketFamilyMet": 1210.00,
        },
    },
    "MEM-778899": {
        "memberId": "MEM-778899",
        "subscriberId": "SUB-778899",
        "firstName": "Priya",
        "lastName": "Natarajan",
        "dateOfBirth": "1991-06-25",
        "phone": "+15555550103",
        "relationship": "Subscriber",
        "groupId": "GRP-1001",
        "groupName": "Northwind Traders",
        "planId": "PPO1500",
        "planDescription": "Enterprise Choice PPO 1500",
        "productType": "PPO",
        "status": "Terminated",
        "coverageEffectiveDate": "2024-01-01",
        "coverageTermDate": "2026-06-30",
        "pcp": None,
        "accumulators": {
            "deductibleIndividualTotal": 1500.00,
            "deductibleIndividualMet": 300.00,
            "deductibleFamilyTotal": 3000.00,
            "deductibleFamilyMet": 300.00,
            "outOfPocketIndividualTotal": 4000.00,
            "outOfPocketIndividualMet": 300.00,
            "outOfPocketFamilyTotal": 8000.00,
            "outOfPocketFamilyMet": 300.00,
        },
    },
}

PROVIDERS = {
    "1234567893": {
        "npi": "1234567893",
        "taxId": "998877665",
        "name": "Riverside Family Medicine",
        "renderingProvider": "Dr. Alana Brooks",
        "specialty": "Family Medicine",
        "networkStatus": "In-Network",
        "contractTier": "Tier 1 - Preferred",
        "credentialingStatus": "Credentialed",
        "recredentialingDue": "2027-04-30",
        "phone": "+15555550190",
    },
    "1987654320": {
        "npi": "1987654320",
        "taxId": "112233445",
        "name": "Lakeshore Imaging Center",
        "renderingProvider": None,
        "specialty": "Diagnostic Radiology",
        "networkStatus": "In-Network",
        "contractTier": "Tier 2 - Standard",
        "credentialingStatus": "Credentialed",
        "recredentialingDue": "2026-12-31",
        "phone": "+15555550191",
    },
    "1555555555": {
        "npi": "1555555555",
        "taxId": "556677889",
        "name": "Summit Orthopedic Group",
        "renderingProvider": None,
        "specialty": "Orthopedic Surgery",
        "networkStatus": "Out-of-Network",
        "contractTier": "None",
        "credentialingStatus": "Pending - application received 2026-09-15",
        "recredentialingDue": None,
        "phone": "+15555550192",
    },
}

# FACETS-style explanation (EX) codes. Descriptions are written for this mock.
EXPLANATION_CODES = {
    "EX-01": "Paid according to the provider's contracted rate.",
    "EX-17": "Additional information requested. Please submit the itemized bill and medical records.",
    "EX-29": "The time limit for filing has expired. Claims must be received within 180 days of the date of service.",
    "EX-43": "Duplicate billing. This service has already been processed on a prior claim.",
    "EX-52": "Prior authorization was required and was not obtained for this service.",
    "EX-60": "The member's coverage was not active on the date of service.",
}

CLAIMS = {
    "CLM-112233": {
        "claimId": "CLM-112233",
        "providerNpi": "1234567893",
        "providerTaxId": "998877665",
        "patientMemberId": "MEM-987654",
        "dateOfService": "2026-08-14",
        "receivedDate": "2026-08-20",
        "procedureCodes": ["99214"],
        "totalBilledAmount": 450.00,
        "allowedAmount": 0.00,
        "paidAmount": 0.00,
        "memberResponsibility": 0.00,
        "adjudicationStatus": "DENIED",
        "explanationCode": "EX-43",
        "adjudicatedDate": "2026-08-27",
        "checkNumber": None,
        "originalClaimId": "CLM-112200",
    },
    "CLM-112200": {
        "claimId": "CLM-112200",
        "providerNpi": "1234567893",
        "providerTaxId": "998877665",
        "patientMemberId": "MEM-987654",
        "dateOfService": "2026-08-14",
        "receivedDate": "2026-08-16",
        "procedureCodes": ["99214"],
        "totalBilledAmount": 450.00,
        "allowedAmount": 210.00,
        "paidAmount": 180.00,
        "memberResponsibility": 30.00,
        "adjudicationStatus": "PAID",
        "explanationCode": "EX-01",
        "adjudicatedDate": "2026-08-22",
        "checkNumber": "EFT-55120934",
        "originalClaimId": None,
    },
    "CLM-334455": {
        "claimId": "CLM-334455",
        "providerNpi": "1987654320",
        "providerTaxId": "112233445",
        "patientMemberId": "MEM-445566",
        "dateOfService": "2026-09-03",
        "receivedDate": "2026-09-10",
        "procedureCodes": ["70553"],
        "totalBilledAmount": 2800.00,
        "allowedAmount": None,
        "paidAmount": None,
        "memberResponsibility": None,
        "adjudicationStatus": "PENDED",
        "explanationCode": "EX-17",
        "adjudicatedDate": None,
        "checkNumber": None,
        "originalClaimId": None,
    },
    "CLM-556677": {
        "claimId": "CLM-556677",
        "providerNpi": "1987654320",
        "providerTaxId": "112233445",
        "patientMemberId": "MEM-987654",
        "dateOfService": "2026-07-21",
        "receivedDate": "2026-07-25",
        "procedureCodes": ["73721"],
        "totalBilledAmount": 1650.00,
        "allowedAmount": 0.00,
        "paidAmount": 0.00,
        "memberResponsibility": 0.00,
        "adjudicationStatus": "DENIED",
        "explanationCode": "EX-52",
        "adjudicatedDate": "2026-08-02",
        "checkNumber": None,
        "originalClaimId": None,
    },
    "CLM-667788": {
        "claimId": "CLM-667788",
        "providerNpi": "1234567893",
        "providerTaxId": "998877665",
        "patientMemberId": "MEM-445566",
        "dateOfService": "2026-09-18",
        "receivedDate": "2026-09-19",
        "procedureCodes": ["99213"],
        "totalBilledAmount": 185.00,
        "allowedAmount": 120.00,
        "paidAmount": 100.00,
        "memberResponsibility": 20.00,
        "adjudicationStatus": "PAID",
        "explanationCode": "EX-01",
        "adjudicatedDate": "2026-09-25",
        "checkNumber": "EFT-55188420",
        "originalClaimId": None,
    },
}

PRIOR_AUTHS = {
    "PA-20260901": {
        "authId": "PA-20260901",
        "memberId": "MEM-445566",
        "requestingProviderNpi": "1987654320",
        "procedureCode": "70553",
        "procedureDescription": "MRI brain with and without contrast",
        "status": "APPROVED",
        "requestedDate": "2026-08-28",
        "decisionDate": "2026-08-30",
        "validFrom": "2026-08-30",
        "validThrough": "2026-11-30",
        "unitsApproved": 1,
    },
    "PA-20260915": {
        "authId": "PA-20260915",
        "memberId": "MEM-987654",
        "requestingProviderNpi": "1555555555",
        "procedureCode": "27447",
        "procedureDescription": "Total knee arthroplasty",
        "status": "IN_REVIEW",
        "requestedDate": "2026-09-15",
        "decisionDate": None,
        "validFrom": None,
        "validThrough": None,
        "unitsApproved": None,
    },
}

# Benefit rules by plan and CPT/HCPCS code.
PROCEDURES = {
    "99213": "Office visit, established patient, low complexity",
    "99214": "Office visit, established patient, moderate complexity",
    "70553": "MRI brain with and without contrast",
    "73721": "MRI lower extremity joint without contrast",
    "27447": "Total knee arthroplasty",
    "97110": "Physical therapy, therapeutic exercise",
    "90834": "Psychotherapy, 45 minutes",
}

BENEFIT_RULES = {
    "PPO1500": {
        "99213": {"covered": True, "priorAuthRequired": False, "inNetwork": {"copay": 30.0}, "outOfNetwork": {"coinsurancePct": 40, "subjectToDeductible": True}},
        "99214": {"covered": True, "priorAuthRequired": False, "inNetwork": {"copay": 30.0}, "outOfNetwork": {"coinsurancePct": 40, "subjectToDeductible": True}},
        "70553": {"covered": True, "priorAuthRequired": True, "inNetwork": {"coinsurancePct": 20, "subjectToDeductible": True}, "outOfNetwork": {"coinsurancePct": 40, "subjectToDeductible": True}},
        "73721": {"covered": True, "priorAuthRequired": True, "inNetwork": {"coinsurancePct": 20, "subjectToDeductible": True}, "outOfNetwork": {"coinsurancePct": 40, "subjectToDeductible": True}},
        "27447": {"covered": True, "priorAuthRequired": True, "inNetwork": {"coinsurancePct": 20, "subjectToDeductible": True}, "outOfNetwork": {"coinsurancePct": 40, "subjectToDeductible": True}},
        "97110": {"covered": True, "priorAuthRequired": False, "visitLimit": 30, "visitsUsed": 6, "inNetwork": {"copay": 40.0}, "outOfNetwork": {"coinsurancePct": 40, "subjectToDeductible": True}},
        "90834": {"covered": True, "priorAuthRequired": False, "inNetwork": {"copay": 30.0}, "outOfNetwork": {"coinsurancePct": 40, "subjectToDeductible": True}},
    },
    "HMO500": {
        "99213": {"covered": True, "priorAuthRequired": False, "referralRequired": False, "inNetwork": {"copay": 20.0}, "outOfNetwork": {"covered": False}},
        "99214": {"covered": True, "priorAuthRequired": False, "referralRequired": False, "inNetwork": {"copay": 20.0}, "outOfNetwork": {"covered": False}},
        "70553": {"covered": True, "priorAuthRequired": True, "referralRequired": True, "inNetwork": {"copay": 250.0}, "outOfNetwork": {"covered": False}},
        "73721": {"covered": True, "priorAuthRequired": True, "referralRequired": True, "inNetwork": {"copay": 250.0}, "outOfNetwork": {"covered": False}},
        "27447": {"covered": True, "priorAuthRequired": True, "referralRequired": True, "inNetwork": {"coinsurancePct": 10, "subjectToDeductible": True}, "outOfNetwork": {"covered": False}},
        "97110": {"covered": True, "priorAuthRequired": True, "referralRequired": True, "visitLimit": 20, "visitsUsed": 0, "inNetwork": {"copay": 30.0}, "outOfNetwork": {"covered": False}},
        "90834": {"covered": True, "priorAuthRequired": False, "referralRequired": False, "inNetwork": {"copay": 20.0}, "outOfNetwork": {"covered": False}},
    },
}
